services:
  - type: web
    name: smartconvert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn smartconvert.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smartconvert.settings
